(() => {
'use strict';
const $=id=>document.getElementById(id),CORE=()=>window.GameGuessCore,FB=()=>window.GameGuessFirebase;
let unsub=null,searchTimer=0,lastData={friends:[],requests:[],invites:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(a,b,t=''){CORE()?.toast?.(a,b,t)}
function currentInviteContext(game){
  if(game==='kof')return localStorage.getItem('gameGuessLastKofRoom')||'';
  if(game==='arena')return localStorage.getItem('gameGuessLastDuel')||'';
  if(game==='geoguess')return localStorage.getItem('gameGuessLastGeoRoom')||'';
  return '';
}
function inject(){
  const main=document.querySelector('main.shell');if(!main||$('friendsScreen'))return;
  const top=document.querySelector('.top-actions');if(top){const b=document.createElement('button');b.className='mini-pill';b.id='friendsButton';b.title='Amigos e convites';b.innerHTML='👥 <b>Amigos</b>';top.insertBefore(b,$('avatarButton')||$('profileButton')||$('achievementsButton'));}
  main.insertAdjacentHTML('beforeend',`<section class="screen friends-screen" id="friendsScreen"><div class="section-heading"><button class="back-link" id="friendsBack">← Voltar</button><div><p class="eyebrow">👥 SOCIAL V17</p><h2>Amigos e convites</h2><p>Adicione jogadores, veja quem está online e convide direto para KOF, Arena ou GeoGuess.</p></div></div><div class="friends-layout"><section class="friends-panel"><h3>🔎 Adicionar amigo</h3><div class="friend-search"><input id="friendSearchInput" maxlength="30" placeholder="Digite o nickname"><button class="secondary-btn" id="friendSearchButton">BUSCAR</button></div><div id="friendSearchResults" class="friend-list"><div class="friend-empty">Busque pelo nickname do jogador.</div></div></section><section class="friends-panel"><div class="friends-panel-head"><h3>🤝 Seus amigos</h3><select id="friendInviteGame"><option value="kof">🥊 KOF 2002</option><option value="arena">⚔️ Arena Online</option><option value="geoguess">🌍 GeoGuess</option></select></div><div id="friendsList" class="friend-list"></div></section><section class="friends-panel"><h3>📨 Pedidos</h3><div id="friendRequestsList" class="friend-list"></div></section><section class="friends-panel"><h3>🎮 Convites para jogar</h3><div id="gameInvitesList" class="friend-list"></div></section></div></section>`);
}
function onlineBadge(v){return `<span class="friend-status ${v?'online':'offline'}">${v?'● ONLINE':'● OFFLINE'}</span>`}
function render(data=lastData){lastData=data||lastData;
  const friends=$('friendsList'),requests=$('friendRequestsList'),invites=$('gameInvitesList');
  if(friends)friends.innerHTML=(data.friends||[]).map(f=>`<article class="friend-card"><div class="friend-avatar">${onlineBadge(f.online)}<span>👤</span></div><div><b>${esc(f.name||'Jogador')}</b><small>${esc(f.favoriteGame||'Game Guess')}</small></div><div class="friend-actions"><button data-invite="${esc(f.uid)}">🎮 CONVIDAR</button><button class="danger-lite" data-remove-friend="${esc(f.uid)}">REMOVER</button></div></article>`).join('')||'<div class="friend-empty">Você ainda não adicionou amigos.</div>';
  if(requests)requests.innerHTML=(data.requests||[]).map(r=>`<article class="friend-card compact"><div class="friend-avatar"><span>👋</span></div><div><b>${esc(r.fromName||'Jogador')}</b><small>Quer adicionar você.</small></div><div class="friend-actions"><button data-request-accept="${esc(r.fromUid)}">ACEITAR</button><button class="danger-lite" data-request-decline="${esc(r.fromUid)}">RECUSAR</button></div></article>`).join('')||'<div class="friend-empty">Nenhum pedido pendente.</div>';
  if(invites)invites.innerHTML=(data.invites||[]).map(i=>{const game=i.game==='kof'?'🥊 KOF 2002':i.game==='geoguess'?'🌍 GeoGuess':'⚔️ Arena Online';return `<article class="friend-card compact invite"><div class="friend-avatar"><span>🎮</span></div><div><b>${esc(i.fromName||'Jogador')}</b><small>${game}${i.roomCode?` • Sala ${esc(i.roomCode)}`:' • convite para jogar'}</small></div><div class="friend-actions"><button data-invite-accept="${esc(i.fromUid)}" data-game="${esc(i.game)}" data-code="${esc(i.roomCode||'')}">ENTRAR</button><button class="danger-lite" data-invite-dismiss="${esc(i.fromUid)}">FECHAR</button></div></article>`}).join('')||'<div class="friend-empty">Nenhum convite ativo.</div>';
}
async function refresh(){try{const d=await FB()?.getSocialData?.();if(d)render(d)}catch(e){console.warn('Social refresh:',e)}}
function open(){if(!FB()?.getUser?.()){FB()?.openAuth?.('login');return toast('Login necessário','Entre na sua conta para usar amigos e convites.','error')}CORE()?.showScreen?.('friendsScreen');unsub?.();unsub=FB()?.watchSocialInbox?.(render)||null;refresh()}
async function search(){const q=String($('friendSearchInput')?.value||'').trim(),box=$('friendSearchResults');if(q.length<2){if(box)box.innerHTML='<div class="friend-empty">Digite pelo menos 2 caracteres.</div>';return}if(box)box.innerHTML='<div class="friend-empty">Buscando jogadores…</div>';try{const rows=await FB().searchPlayers(q);box.innerHTML=rows.map(x=>`<article class="friend-card compact"><div class="friend-avatar">${onlineBadge(x.online)}<span>👤</span></div><div><b>${esc(x.name||x.nickname||'Jogador')}</b><small>${x.isFriend?'Já é seu amigo':esc(x.favoriteGame||'Game Guess')}</small></div><div class="friend-actions">${x.isFriend?'<button disabled>ADICIONADO</button>':`<button data-add-friend="${esc(x.uid)}">+ ADICIONAR</button>`}</div></article>`).join('')||'<div class="friend-empty">Nenhum jogador encontrado.</div>'}catch(e){box.innerHTML=`<div class="friend-empty">${esc(e.message||'Falha na busca.')}</div>`}}
async function sendInvite(uid){const game=$('friendInviteGame')?.value||'kof',roomCode=currentInviteContext(game);try{await FB().sendGameInvite(uid,{game,roomCode});toast('Convite enviado',roomCode?`Seu amigo recebeu o convite para a sala ${roomCode}.`:'Seu amigo recebeu um convite para jogar.')}catch(e){toast('Convite',e.message||String(e),'error')}}
async function acceptInvite(fromUid,game,code){try{await FB().dismissGameInvite(fromUid);unsub?.();unsub=null;CORE()?.showScreen?.('homeScreen');if(game==='kof'){$('homeKofButton')?.click();if(code)setTimeout(()=>{const i=$('kofJoinCode');if(i)i.value=code;$('kofJoinRoom')?.click()},180)}else if(game==='arena'){$('homeDuelButton')?.click();if(code)setTimeout(()=>{const i=$('joinDuelCode');if(i)i.value=code;$('joinDuelButton')?.click()},180)}else if(game==='geoguess'){$('homeGeoArenaButton')?.click();if(code)setTimeout(()=>{const i=$('geoJoinCode');if(i)i.value=code;$('geoJoinRoom')?.click()},220)}}catch(e){toast('Convite',e.message||String(e),'error')}}
function bind(){inject();$('friendsButton')?.addEventListener('click',open);$('friendsBack')?.addEventListener('click',()=>{unsub?.();unsub=null;CORE()?.showScreen?.('homeScreen')});$('friendSearchButton')?.addEventListener('click',search);$('friendSearchInput')?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(search,450)});$('friendSearchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('friendsScreen')?.addEventListener('click',async e=>{const add=e.target.closest('[data-add-friend]');if(add){try{await FB().sendFriendRequest(add.dataset.addFriend);toast('Pedido enviado','O jogador verá seu pedido de amizade.');search()}catch(err){toast('Amigos',err.message||String(err),'error')}return}const acc=e.target.closest('[data-request-accept]');if(acc){await FB().respondFriendRequest(acc.dataset.requestAccept,true).catch(err=>toast('Amigos',err.message,'error'));return refresh()}const dec=e.target.closest('[data-request-decline]');if(dec){await FB().respondFriendRequest(dec.dataset.requestDecline,false).catch(()=>{});return refresh()}const rm=e.target.closest('[data-remove-friend]');if(rm){await FB().removeFriend(rm.dataset.removeFriend).catch(()=>{});return refresh()}const inv=e.target.closest('[data-invite]');if(inv)return sendInvite(inv.dataset.invite);const ai=e.target.closest('[data-invite-accept]');if(ai)return acceptInvite(ai.dataset.inviteAccept,ai.dataset.game,ai.dataset.code);const di=e.target.closest('[data-invite-dismiss]');if(di){await FB().dismissGameInvite(di.dataset.inviteDismiss).catch(()=>{});return refresh()}});window.addEventListener('gameguess:authchange',e=>{if(!e.detail?.user){unsub?.();unsub=null}else if($('friendsScreen')?.classList.contains('active'))open()})}
window.GameGuessFriends={open,refresh};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
