(() => {
'use strict';
const $=id=>document.getElementById(id), CORE=()=>window.GameGuessCore, FB=()=>window.GameGuessFirebase;
const REGIONS={world:['🌍','Mundo todo'],americas:['🌎','Américas'],europe:['🏰','Europa'],asia:['🌏','Ásia'],africa:['🦁','África'],oceania:['🌊','Oceania']};
let config={region:'world',rounds:5,maxPlayers:2},solo=null,map=null,guessMarker=null,targetMarker=null,line=null,selected=null,roomCode='',room=null,unsub=null,mode='solo',lastRenderedRound=-1,advanceScheduled=-1,tick=null;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
function show(id){if(!$(id)?.classList.contains('active'))CORE()?.showScreen?.(id);setTimeout(()=>map?.invalidateSize?.(),100)}
function toast(a,b,t=''){CORE()?.toast?.(a,b,t)}
function inject(){const main=document.querySelector('main.shell');if(!main||$('geoSetupScreen'))return;const home=$('homeScreen');if(home){const banner=document.createElement('section');banner.className='geo-home-banner';banner.innerHTML=`<div class="geo-home-icon">🌍</div><div><p class="eyebrow">🧭 GEOGUESS ARENA</p><h2>Descubra onde você está no mundo</h2><p>Fotos geolocalizadas, mapa interativo, pontuação por distância e partidas online para 2 a 8 jogadores.</p></div><div class="geo-home-actions"><button class="primary-btn" id="homeGeoButton">🌍 JOGAR GEOGUESS</button><button class="secondary-btn" id="homeGeoArenaButton">⚔️ CRIAR ARENA</button></div>`;const social=home.querySelector('.social-home-banner'),quiz=home.querySelector('.quiz-home-banner');home.insertBefore(banner,social||quiz||home.firstChild);}
 main.insertAdjacentHTML('beforeend',`<section class="screen geo-setup-screen" id="geoSetupScreen"><div class="section-heading"><button class="back-link" id="geoBack">← Voltar</button><div><p class="eyebrow">🌍 GEOGUESS ARENA</p><h2>Onde no mundo?</h2><p>Observe a imagem, marque sua aposta no mapa e pontue pela proximidade.</p></div></div><div class="geo-setup-layout"><section class="geo-setup-card"><h3>🎮 Partida solo</h3><label>Região<select id="geoRegion"></select></label><label>Rodadas<select id="geoRounds"><option value="3">3 rodadas</option><option value="5" selected>5 rodadas</option><option value="8">8 rodadas</option></select></label><button class="primary-btn huge" id="geoSoloStart">INICIAR SOLO ▶</button></section><section class="geo-setup-card"><h3>⚔️ Arena online</h3><label>Jogadores<select id="geoMaxPlayers">${[2,3,4,5,6,7,8].map(n=>`<option value="${n}">${n} jogadores${n===2?' — 1x1':''}</option>`).join('')}</select></label><div class="geo-room-actions"><button class="primary-btn" id="geoCreateRoom">CRIAR SALA</button><div class="geo-join"><input id="geoJoinCode" maxlength="6" placeholder="ABC123"><button class="secondary-btn" id="geoJoinRoom">ENTRAR</button></div></div><small>Todos recebem as mesmas imagens e têm 60 segundos por rodada.</small></section><section class="geo-waiting hidden" id="geoWaiting"><div class="geo-room-code"><span>SALA</span><b id="geoRoomCode">------</b><button class="icon-btn" id="geoCopyCode">📋</button></div><div id="geoWaitingPlayers" class="geo-waiting-players"></div><div id="geoWaitingStatus"></div><button class="primary-btn huge" id="geoStartRoom">INICIAR PARTIDA</button><button class="secondary-btn" id="geoLeaveRoom">SAIR DA SALA</button></section></div></section>
 <section class="screen geo-game-screen" id="geoGameScreen"><div class="geo-game-top"><button class="back-link" id="geoQuit">← Sair</button><div class="geo-game-metrics"><span id="geoModeBadge">🌍 SOLO</span><span>🧭 <b id="geoRoundLabel">1/5</b></span><span>⭐ <b id="geoScoreLabel">0</b></span><span id="geoTimerLabel">⏱️ --</span></div></div><div class="geo-stage"><section class="geo-photo-card"><div class="geo-photo-wrap"><img id="geoPhoto" alt="Imagem geolocalizada para adivinhar"><div class="geo-photo-loading" id="geoPhotoLoading">🌍 Carregando local...</div></div><div class="geo-photo-note" id="geoPhotoNote">Observe os detalhes da imagem.</div></section><section class="geo-map-card"><div id="geoMap" class="geo-map"></div><div class="geo-map-actions"><button class="primary-btn" id="geoSubmitGuess" disabled>📍 CONFIRMAR LOCAL</button><button class="primary-btn hidden" id="geoNextRound">PRÓXIMA RODADA ▶</button></div><div id="geoFeedback" class="geo-feedback">Toque no mapa para marcar seu palpite.</div></section><section class="geo-scoreboard hidden" id="geoScoreboard"><h3>🏆 Placar da Arena</h3><div id="geoScoreRows"></div></section></div></section>`);
 const sel=$('geoRegion');sel.innerHTML=Object.entries(REGIONS).map(([k,[i,n]])=>`<option value="${k}">${i} ${n}</option>`).join('');}
function ensureMap(){if(map||!window.L||!$('geoMap'))return;map=L.map('geoMap',{worldCopyJump:true,minZoom:2}).setView([15,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);map.on('click',e=>{if(isLocked())return;selected={lat:e.latlng.lat,lng:e.latlng.lng};if(guessMarker)guessMarker.setLatLng(e.latlng);else guessMarker=L.marker(e.latlng).addTo(map);$('geoSubmitGuess').disabled=false;$('geoFeedback').textContent=`📍 Palpite marcado: ${e.latlng.lat.toFixed(2)}, ${e.latlng.lng.toFixed(2)}`;});}
function clearMarkers(){if(!map)return;for(const x of [guessMarker,targetMarker,line])if(x)map.removeLayer(x);guessMarker=targetMarker=line=null;selected=null;map.setView([15,0],2);}
function hav(a,b,c,d){const R=6371,to=x=>x*Math.PI/180,dLat=to(c-a),dLon=to(d-b),x=Math.sin(dLat/2)**2+Math.cos(to(a))*Math.cos(to(c))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function scoreDistance(km){return Math.max(0,Math.round(5000*Math.exp(-km/1800)));}
async function fetchRounds(){const r=await fetch(`/api/geoguess?region=${encodeURIComponent(config.region)}&count=${config.rounds}`,{cache:'no-store'});const d=await r.json();if(!r.ok||!Array.isArray(d.questions)||d.questions.length<config.rounds)throw new Error(d.error||'Não consegui preparar os locais.');return d.questions;}
function currentQ(){return mode==='solo'?solo?.questions?.[solo.index]:room?.questions?.[Number(room.roundIndex||0)]}
function isLocked(){if(mode==='solo')return Boolean(solo?.answered);const me=myPlayer();return !room||room.status!=='playing'||Number(me?.submittedRound)===Number(room.roundIndex);}
function displayRound(){ensureMap();clearMarkers();const q=currentQ();if(!q)return;const idx=mode==='solo'?solo.index:Number(room.roundIndex||0),total=mode==='solo'?solo.questions.length:Number(room.config?.rounds||room.questions?.length||5);$('geoRoundLabel').textContent=`${idx+1}/${total}`;$('geoScoreLabel').textContent=mode==='solo'?solo.score:Number(myPlayer()?.score||0);$('geoModeBadge').textContent=mode==='solo'?'🌍 SOLO':`⚔️ SALA ${roomCode}`;$('geoPhotoLoading').classList.remove('hidden');$('geoPhoto').classList.remove('loaded');$('geoPhoto').src=q.image;$('geoPhoto').onload=()=>{$('geoPhotoLoading').classList.add('hidden');$('geoPhoto').classList.add('loaded')};$('geoPhotoNote').textContent='Observe arquitetura, relevo, vegetação, placas e outros detalhes.';$('geoFeedback').textContent='Toque no mapa para marcar seu palpite.';$('geoSubmitGuess').classList.remove('hidden');$('geoSubmitGuess').disabled=true;$('geoNextRound').classList.add('hidden');selected=null;if(mode==='arena')renderScoreboard();setTimeout(()=>map.invalidateSize(),80);}
function reveal(q,guess,km,pts){if(!map)return;const target=[Number(q.lat),Number(q.lng)],g=[Number(guess.lat),Number(guess.lng)];targetMarker=L.marker(target).addTo(map).bindPopup(`📍 ${esc(q.revealTitle||q.city)} • ${esc(q.country)}`);line=L.polyline([g,target],{weight:3,opacity:.7,dashArray:'8 8'}).addTo(map);map.fitBounds(L.latLngBounds([g,target]).pad(.25),{maxZoom:6});$('geoPhotoNote').innerHTML=`📍 <b>${esc(q.revealTitle||q.city)}</b> • ${esc(q.country)}`;$('geoFeedback').innerHTML=`Distância: <b>${Math.round(km).toLocaleString('pt-BR')} km</b> • <strong>+${pts.toLocaleString('pt-BR')} pontos</strong>`;}
function awardCoins(amount){const p=CORE()?.getProfile?.()||{};p.coins=Number(p.coins||0)+Math.max(0,Math.round(amount));CORE()?.replaceProfile?.(p);CORE()?.saveProfile?.();FB()?.syncLocalProfile?.(p);}
async function startSolo(){config.region=$('geoRegion').value;config.rounds=Number($('geoRounds').value)||5;const b=$('geoSoloStart');b.disabled=true;b.textContent='BUSCANDO LOCAIS...';try{const questions=await fetchRounds();mode='solo';solo={questions,index:0,score:0,answered:false};show('geoGameScreen');setTimeout(displayRound,80)}catch(e){toast('GeoGuess indisponível',e.message||String(e),'error')}finally{b.disabled=false;b.textContent='INICIAR SOLO ▶';}}
function submitSolo(){if(!selected||solo?.answered)return;const q=currentQ(),km=hav(selected.lat,selected.lng,q.lat,q.lng),pts=scoreDistance(km);solo.answered=true;solo.score+=pts;$('geoScoreLabel').textContent=solo.score;reveal(q,selected,km,pts);$('geoSubmitGuess').classList.add('hidden');$('geoNextRound').classList.remove('hidden');awardCoins(Math.max(1,Math.min(6,Math.round(pts/1000))));}
function nextSolo(){if(!solo)return;if(solo.index>=solo.questions.length-1){const p=CORE()?.getProfile?.()||{};p.gamesPlayed=Number(p.gamesPlayed||0)+1;p.gamesWon=Number(p.gamesWon||0)+1;p.geoPlayed=Number(p.geoPlayed||0)+1;p.geoBestScore=Math.max(Number(p.geoBestScore||0),solo.score);p.highScore=Math.max(Number(p.highScore||0),solo.score);p.coins=Number(p.coins||0)+4;window.GameGuessRanked?.record?.(p,{kind:'geoguess',score:solo.score,mode:'solo',universe:'geoguess',challenge:config.region,difficulty:'geografia',correct:solo.questions.length,wrong:0,won:true});CORE()?.replaceProfile?.(p);CORE()?.saveProfile?.();FB()?.syncLocalProfile?.(p);CORE()?.spawnConfetti?.();toast('GeoGuess concluído',`${solo.score.toLocaleString('pt-BR')} pontos • +4 pontos de personalização`);solo=null;return show('geoSetupScreen');}solo.index++;solo.answered=false;displayRound();}
function user(){return FB()?.getUser?.()}
function players(){return Object.values(room?.players||{}).filter(p=>!p.left).sort((a,b)=>Number(a.slot||99)-Number(b.slot||99))}
function myPlayer(){const u=user();return u?room?.players?.[u.uid]:null}
function online(uid){return Object.keys(room?.presence?.[uid]||{}).length>0}
function renderWaiting(){if(!room)return;$('geoWaiting').classList.remove('hidden');$('geoRoomCode').textContent=roomCode;$('geoWaitingPlayers').innerHTML=players().map(p=>`<div><span>${p.uid===room.hostUid?'👑':'🌍'}</span><b>${esc(p.name)}</b><small>${online(p.uid)?'🟢 online':'🟡 reconectando'}</small></div>`).join('');$('geoWaitingStatus').textContent=`${players().length}/${room.config?.maxPlayers||2} jogadores na sala`;$('geoStartRoom').classList.toggle('hidden',room.hostUid!==user()?.uid);$('geoStartRoom').disabled=players().length<2;}
function renderScoreboard(){if(mode!=='arena'||!room)return;$('geoScoreboard').classList.remove('hidden');$('geoScoreRows').innerHTML=players().sort((a,b)=>Number(b.score||0)-Number(a.score||0)).map((p,i)=>`<div><span>#${i+1}</span><b>${esc(p.name)}</b><small>${Number(p.submittedRound)===Number(room.roundIndex)?`✅ ${Math.round(Number(p.distanceKm||0))} km`:'⏳ escolhendo'}</small><strong>${Number(p.score||0).toLocaleString('pt-BR')}</strong></div>`).join('');}
async function createRoom(){if(!user())return toast('Login necessário','Entre na sua conta para criar uma Arena GeoGuess.','error');config.region=$('geoRegion').value;config.rounds=Number($('geoRounds').value)||5;config.maxPlayers=Number($('geoMaxPlayers').value)||2;const b=$('geoCreateRoom');b.disabled=true;b.textContent='CRIANDO...';try{const questions=await fetchRounds();roomCode=await FB().createGeoRoom({questions,region:config.region,maxPlayers:config.maxPlayers});mode='arena';watchRoom(roomCode);$('geoWaiting').classList.remove('hidden');toast('Sala criada',`Código ${roomCode}`)}catch(e){toast('Erro ao criar sala',e.message||String(e),'error')}finally{b.disabled=false;b.textContent='CRIAR SALA';}}
async function joinRoom(){if(!user())return toast('Login necessário','Entre na sua conta para entrar na Arena GeoGuess.','error');const code=String($('geoJoinCode').value||'').trim().toUpperCase();try{roomCode=await FB().joinGeoRoom(code);mode='arena';watchRoom(roomCode);$('geoWaiting').classList.remove('hidden');toast('Conectado',`Você entrou em ${roomCode}`)}catch(e){toast('Não consegui entrar',e.message||String(e),'error')}}
function watchRoom(code){unsub?.();unsub=FB().watchGeoRoom(code,(r,e)=>{if(e)return toast('GeoGuess',e.message||'Falha na sala.','error');room=r;if(!r){roomCode='';$('geoWaiting')?.classList.add('hidden');return;}FB()?.ensureGeoHost?.(code);if(r.status==='waiting'){show('geoSetupScreen');renderWaiting()}else if(r.status==='playing'){show('geoGameScreen');const idx=Number(r.roundIndex||0);if(lastRenderedRound!==idx){lastRenderedRound=idx;displayRound()}else{renderScoreboard();maybeRevealArena();}ensureArenaTicker()}else if(r.status==='finished'){show('geoGameScreen');renderScoreboard();finishArena();}})}
async function startRoom(){try{await FB().startGeoRoom(roomCode)}catch(e){toast('Não consegui iniciar',e.message||String(e),'error')}}
async function submitArena(){if(!selected||isLocked())return;const q=currentQ(),idx=Number(room.roundIndex||0),km=hav(selected.lat,selected.lng,q.lat,q.lng),pts=scoreDistance(km),g={...selected};$('geoSubmitGuess').disabled=true;try{await FB().mutateGeoRoom(roomCode,(r,uid)=>{const p=r.players?.[uid];if(!p||Number(p.submittedRound)===idx||Number(r.roundIndex)!==idx)return;p.submittedRound=idx;p.guessLat=g.lat;p.guessLng=g.lng;p.distanceKm=Math.round(km*10)/10;p.roundScore=pts;p.score=Number(p.score||0)+pts;return r;});awardCoins(Math.max(1,Math.min(5,Math.round(pts/1200))))}catch(e){toast('Palpite',e.message||String(e),'error')}}
function allSubmitted(){const idx=Number(room?.roundIndex||0);return players().length>0&&players().every(p=>Number(p.submittedRound)===idx)}
function maybeRevealArena(){if(!room||room.status!=='playing')return;const me=myPlayer(),idx=Number(room.roundIndex||0),q=currentQ();if(Number(me?.submittedRound)===idx&&me?.guessLat!=null&&!targetMarker)reveal(q,{lat:me.guessLat,lng:me.guessLng},Number(me.distanceKm||0),Number(me.roundScore||0));if(allSubmitted()&&room.hostUid===user()?.uid&&advanceScheduled!==idx){advanceScheduled=idx;setTimeout(()=>advanceArena(idx),4000)}}
async function advanceArena(idx){if(!room||room.status!=='playing'||Number(room.roundIndex)!==idx||room.hostUid!==user()?.uid)return;try{await FB().mutateGeoRoom(roomCode,(r)=>{if(Number(r.roundIndex)!==idx)return r;const total=Number(r.config?.rounds||r.questions?.length||5);if(idx>=total-1){r.status='finished';r.roundState='finished';r.finishedAt=Date.now();r.expiresAt=Date.now()+2*60*60*1000;const list=Object.values(r.players||{}).sort((a,b)=>Number(b.score||0)-Number(a.score||0));r.winnerUid=list[0]?.uid||'';return r;}r.roundIndex=idx+1;r.roundDeadline=Date.now()+60000;r.roundState='playing';return r;});}catch{}}
function ensureArenaTicker(){if(tick)return;tick=setInterval(async()=>{if(!room||room.status!=='playing')return;const left=Math.max(0,Math.ceil((Number(room.roundDeadline||0)-(FB()?.serverNow?.()||Date.now()))/1000));if($('geoTimerLabel'))$('geoTimerLabel').textContent=`⏱️ ${left}`;if(left<=0&&room.hostUid===user()?.uid&&!allSubmitted()){const idx=Number(room.roundIndex||0);await FB().mutateGeoRoom(roomCode,r=>{for(const p of Object.values(r.players||{})){if(Number(p.submittedRound)!==idx){p.submittedRound=idx;p.guessLat=0;p.guessLng=0;p.distanceKm=20000;p.roundScore=0;}}return r;}).catch(()=>{});}},500)}
function finishArena(){if(tick){clearInterval(tick);tick=null}const u=user();if(!u||!room)return;const key=`ggGeoRecorded:${room.code}:${u.uid}`;if(!localStorage.getItem(key)){localStorage.setItem(key,'1');const p=CORE()?.getProfile?.()||{},won=room.winnerUid===u.uid; p.geoPlayed=Number(p.geoPlayed||0)+1;p.geoWins=Number(p.geoWins||0)+(won?1:0);p.gamesPlayed=Number(p.gamesPlayed||0)+1;if(won)p.gamesWon=Number(p.gamesWon||0)+1;p.geoBestScore=Math.max(Number(p.geoBestScore||0),Number(myPlayer()?.score||0));p.coins=Number(p.coins||0)+(won?12:4);window.GameGuessRanked?.record?.(p,{kind:'geoguess-arena',score:Number(myPlayer()?.score||0),mode:`${players().length}-players`,universe:'geoguess',challenge:room.config?.region||'world',difficulty:'arena',correct:Number(room.config?.rounds||0),wrong:0,won,players:players().length});CORE()?.replaceProfile?.(p);CORE()?.saveProfile?.();FB()?.syncLocalProfile?.(p);if(won)CORE()?.spawnConfetti?.();toast(won?'🏆 Você venceu o GeoGuess!':'GeoGuess finalizado',`${Number(myPlayer()?.score||0).toLocaleString('pt-BR')} pontos • +${won?12:4} pontos de personalização`);}const winner=room.players?.[room.winnerUid];$('geoFeedback').innerHTML=`🏆 Vencedor: <b>${esc(winner?.name||'Jogador')}</b> • ${Number(winner?.score||0).toLocaleString('pt-BR')} pontos`;}
async function leaveRoom(){if(roomCode)await FB()?.leaveGeoRoom?.(roomCode).catch(()=>{});unsub?.();unsub=null;room=null;roomCode='';lastRenderedRound=-1;advanceScheduled=-1;$('geoWaiting')?.classList.add('hidden');if(tick){clearInterval(tick);tick=null}show('geoSetupScreen')}
function quit(){if(mode==='arena'&&roomCode)return leaveRoom();solo=null;show('geoSetupScreen')}
function open(arena=false){show('geoSetupScreen');if(arena)setTimeout(()=>$('geoCreateRoom')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}
function bind(){inject();$('homeGeoButton')?.addEventListener('click',()=>open(false));$('homeGeoArenaButton')?.addEventListener('click',()=>open(true));$('geoBack')?.addEventListener('click',()=>show('homeScreen'));$('geoSoloStart')?.addEventListener('click',startSolo);$('geoSubmitGuess')?.addEventListener('click',()=>mode==='solo'?submitSolo():submitArena());$('geoNextRound')?.addEventListener('click',nextSolo);$('geoCreateRoom')?.addEventListener('click',createRoom);$('geoJoinRoom')?.addEventListener('click',joinRoom);$('geoStartRoom')?.addEventListener('click',startRoom);$('geoLeaveRoom')?.addEventListener('click',leaveRoom);$('geoQuit')?.addEventListener('click',quit);$('geoCopyCode')?.addEventListener('click',()=>navigator.clipboard?.writeText(roomCode).then(()=>toast('Código copiado',roomCode)));window.addEventListener('gameguess:authchange',e=>{if(!e.detail?.user&&roomCode)leaveRoom()});}
window.GameGuessGeo={open};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
