(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const qsa=s=>[...document.querySelectorAll(s)];
  const CORE=()=>window.GameGuessCore;
  const PROFILE_KEY='gameGuessArcadeV4';
  const UNIVERSE_API='/api/universe';

  const UNIVERSES={
    lol:{title:'League of Legends',icon:'⚔️',color:'#c99b3b',source:'Riot Data Dragon',desc:'Descubra o campeão pela splash art, função e atributos.',eyebrow:'⚔️ QUAL É O CAMPEÃO?',filters:{title:'⚔️ Função',help:'Filtre pela função principal',items:{all:'Todos',fighter:'Lutador',tank:'Tanque',mage:'Mago',assassin:'Assassino',marksman:'Atirador',support:'Suporte'}}},
    pokemon:{title:'Pokémon',icon:'🔴',color:'#ffcf3f',source:'PokéAPI',desc:'Adivinhe o Pokémon pela arte oficial, tipo, geração e medidas.',eyebrow:'🔴 QUAL É O POKÉMON?',filters:{title:'🧬 Geração',help:'Escolha uma geração ou misture todas',items:{all:'Todas',gen1:'Geração I',gen2:'Geração II',gen3:'Geração III',gen4:'Geração IV',gen5:'Geração V',gen6:'Geração VI',gen7:'Geração VII',gen8:'Geração VIII',gen9:'Geração IX',silhouette:'👤 Silhueta • todas'}}},
    digimon:{title:'Digimon',icon:'🔵',color:'#62a9ff',source:'DAPI',desc:'Descubra o Digimon pela imagem, nível, atributo e tipo.',eyebrow:'🔵 QUAL É O DIGIMON?',filters:{title:'🧬 Nível',help:'A DAPI filtra por nível',items:{all:'Todos',Rookie:'Rookie',Champion:'Champion',Ultimate:'Ultimate',Mega:'Mega',Armor:'Armor'}}},
    dragonball:{title:'Dragon Ball',icon:'🐉',color:'#ff8b29',source:'Curadoria Dragon Ball',desc:'Do Dragon Ball clássico ao Super: reconheça guerreiros, rivais e vilões.',eyebrow:'🐉 QUEM É O PERSONAGEM?',theme:'dragonball',roundTitle:'Do clássico ao Super: reconhece quem é?',filters:{title:'🔥 Série',help:'Escolha a fase de Dragon Ball',items:{all:'Todas',classic:'Dragon Ball clássico',z:'Dragon Ball Z',gt:'Dragon Ball GT',super:'Dragon Ball Super'}}},
    yugioh:{title:'Yu-Gi-Oh!',icon:'🃏',color:'#9b6dff',source:'Curadoria Yu-Gi-Oh!',desc:'Descubra duelistas do clássico e de Yu-Gi-Oh! GX.',eyebrow:'🃏 QUEM É O DUELISTA?',theme:'yugioh',roundTitle:'É hora do duelo. Quem é?',filters:{title:'🧿 Geração',help:'Do clássico até GX',items:{all:'Todas',classic:'Clássico • Duel Monsters',gx:'Yu-Gi-Oh! GX'}}},
    naruto:{title:'Naruto',icon:'🍥',color:'#ff9b42',source:'Curadoria Naruto',desc:'Ninjas do clássico e do Shippuden em desafios de personagem.',eyebrow:'🍥 QUE NINJA É ESSE?',theme:'naruto',roundTitle:'Observe os detalhes e reconheça o ninja.',filters:{title:'🍃 Fase',help:'Escolha a fase da história',items:{all:'Todas',classic:'Naruto clássico',shippuden:'Naruto Shippuden'}}},
    cartoons:{title:'Desenhos clássicos',icon:'📺',color:'#ff72d6',source:'Curadoria + Wikipedia',desc:'Personagens que marcaram a TV e a infância no Brasil.',eyebrow:'📺 QUEM É O PERSONAGEM?',filters:{title:'🧩 Seleção',help:'Curadoria de personagens clássicos no Brasil',items:{all:'Todos'}}},
    globinho:{title:'TV Globinho',icon:'☀️',color:'#68c6ff',source:'Especial TV Globinho',desc:'Tema exclusivo inspirado nas manhãs da TV Globinho.',eyebrow:'☀️ ESPECIAL TV GLOBINHO',globinho:true,theme:'globinho',roundTitle:'Quanto você lembra das manhãs da Globo?',filters:{title:'📡 Especial',help:'Personagens de atrações associadas à TV Globinho',items:{all:'Maratona TV Globinho'}}},
    termo:{title:'Termo Arcade ∞',icon:'🔤',color:'#63e6a5',source:'Palavras PT-BR • infinito',desc:'Adivinhe palavras de 5 letras em até 6 tentativas, sem limite de rodadas.',eyebrow:'♾️ TERMO ARCADE',custom:'termo',theme:'termo'}
  };
  const MODES={classic:{title:'Clássico',icon:'🧠',rounds:20},survival:{title:'Survival',icon:'❤️',rounds:50},blitz:{title:'Blitz',icon:'⏱️',rounds:60}};
  const DIFF={easy:{title:'Fácil',icon:'🌱',attempts:6,pieces:2,mult:.85,mask:.0},normal:{title:'Normal',icon:'🎯',attempts:6,pieces:1,mult:1,mask:.08},hard:{title:'Difícil',icon:'🔥',attempts:5,pieces:0,mult:1.35,mask:.22},insane:{title:'Insano',icon:'💀',attempts:3,pieces:0,mult:1.8,mask:.38}};
  let setup={universe:'lol',mode:'classic',difficulty:'normal',filter:'all'};
  let session=null,ticker=null,resultAction=null,loadingToken=0;

  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
  function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function show(id){CORE()?.showScreen?.(id) || qsa('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'});}
  function toast(a,b,t=''){CORE()?.toast?.(a,b,t);}
  function sound(t){CORE()?.playSound?.(t);}
  function confetti(){CORE()?.spawnConfetti?.();}
  function readProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
  function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p));CORE()?.syncProfile?.();}
  function updateProfileWin(universe,points,streak){const p=readProfile();p.coins=Number(p.coins||0)+Math.max(8,Math.round(points/65));p.highScore=Math.max(Number(p.highScore||0),Number(points||0));p.gamesPlayed=Number(p.gamesPlayed||0)+1;p.gamesWon=Number(p.gamesWon||0)+1;p.bestStreak=Math.max(Number(p.bestStreak||0),streak);p.multiverseWins={...(p.multiverseWins||{})};p.multiverseWins[universe]=Number(p.multiverseWins[universe]||0)+1;p.achievements={...(p.achievements||{})};const wins=p.multiverseWins;const rewards={challenger:160,pokemonMaster:220,digichosen:160,cartoonMemory:160,globinhoKid:180,zWarrior:180,duelKing:180,hokage:180,multiverse:300};const labels={challenger:'⚔️ Challenger',pokemonMaster:'🔴 Mestre Pokémon',digichosen:'🔵 DigiEscolhido',cartoonMemory:'📺 Memória de Elefante',globinhoKid:'☀️ Filho da Globinho',zWarrior:'🐉 Guerreiro Z',duelKing:'🃏 Rei dos Duelos',hokage:'🍥 Caminho do Hokage',multiverse:'🌌 Viajante do Multiverso'};const unlock=(k)=>{if(!p.achievements[k]){p.achievements[k]=Date.now();p.coins+=rewards[k]||0;toast('Conquista desbloqueada!',(labels[k]||k)+` • +${rewards[k]||0} moedas`,'achievement');}};if((wins.lol||0)>=20)unlock('challenger');if((wins.pokemon||0)>=50)unlock('pokemonMaster');if((wins.digimon||0)>=20)unlock('digichosen');if((wins.cartoons||0)>=20)unlock('cartoonMemory');if((wins.globinho||0)>=15)unlock('globinhoKid');if((wins.dragonball||0)>=20)unlock('zWarrior');if((wins.yugioh||0)>=20)unlock('duelKing');if((wins.naruto||0)>=20)unlock('hokage');if(['lol','pokemon','digimon','dragonball','yugioh','naruto','cartoons','globinho'].every(k=>(wins[k]||0)>0))unlock('multiverse');saveProfile(p);}
  function updateProfileLoss(){const p=readProfile();p.gamesPlayed=Number(p.gamesPlayed||0)+1;saveProfile(p);}

  function renderCards(){const grid=$('universeGrid');if(!grid)return;grid.innerHTML='';Object.entries(UNIVERSES).forEach(([key,u])=>{const b=document.createElement('button');b.className='universe-card'+(u.theme?` ${u.theme}`:'');b.style.setProperty('--u-color',u.color);b.innerHTML=`<span class="u-icon">${u.icon}</span><h3>${esc(u.title)}</h3><p>${esc(u.desc)}</p><small>${esc(u.source)} →</small>`;b.onclick=()=>u.custom==='termo'?window.GameGuessTermo?.open?.():openSetup(key);grid.appendChild(b);});}
  function applyTheme(el,key){['globinho','dragonball','yugioh','naruto'].forEach(t=>el.classList.toggle(`${t}-theme`,key===t));}
  function openSetup(key){setup={universe:key,mode:'classic',difficulty:'normal',filter:'all'};applyTheme($('universeSetupScreen'),key);renderSetup();show('universeSetupScreen');}
  function renderSetup(){const u=UNIVERSES[setup.universe];$('universeSetupEyebrow').textContent=`${u.icon} GAME GUESS MULTIVERSO`;$('universeSetupTitle').textContent=u.title;$('universeSetupDesc').textContent=u.desc;$('universeSetupIcon').textContent=u.icon;$('universeSummaryTitle').textContent=u.title;$('universeModeChoices').innerHTML='';Object.entries(MODES).forEach(([k,m])=>{const b=document.createElement('button');b.className='choice-btn'+(setup.mode===k?' active':'');b.innerHTML=`${m.icon} ${m.title}`;b.onclick=()=>{setup.mode=k;renderSetup()};$('universeModeChoices').appendChild(b)});$('universeDifficultyChoices').innerHTML='';Object.entries(DIFF).forEach(([k,d])=>{const b=document.createElement('button');b.className='choice-btn'+(setup.difficulty===k?' active':'');b.innerHTML=`${d.icon} ${d.title}`;b.onclick=()=>{setup.difficulty=k;renderSetup()};$('universeDifficultyChoices').appendChild(b)});$('universeFilterTitle').textContent=u.filters.title;$('universeFilterHelp').textContent=u.filters.help;$('universeFilterChoices').innerHTML='';Object.entries(u.filters.items).forEach(([k,label])=>{const b=document.createElement('button');b.className='choice-btn'+(String(setup.filter).toLowerCase()===String(k).toLowerCase()?' active':'');b.textContent=label;b.onclick=()=>{setup.filter=k;renderSetup()};$('universeFilterChoices').appendChild(b)});const mode=MODES[setup.mode],diff=DIFF[setup.difficulty];$('universeSummaryList').innerHTML=`<div><span>Universo</span><b>${u.icon} ${esc(u.title)}</b></div><div><span>Modo</span><b>${mode.icon} ${mode.title}</b></div><div><span>Dificuldade</span><b>${diff.icon} ${diff.title}</b></div><div><span>Seleção</span><b>${esc(u.filters.items[setup.filter]||setup.filter)}</b></div>`;}

  async function post(body){const r=await fetch(UNIVERSE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d;}
  async function start(){const token=++loadingToken;const u=UNIVERSES[setup.universe],mode=MODES[setup.mode];show('loadingScreen');$('loadingTitle').textContent=`Abrindo ${u.title}...`;$('loadingText').textContent=setup.universe==='globinho'?'Ligando a nostalgia das manhãs da TV Globinho...':`Buscando uma seleção aleatória em ${u.source}...`;try{const d=await post({universe:setup.universe,filter:setup.filter,limit:mode.rounds});if(token!==loadingToken)return;if(!Array.isArray(d.items)||!d.items.length)throw new Error('Nenhum item retornado.');session={config:{...setup},items:shuffle(d.items),index:0,wins:0,losses:0,score:0,streak:0,lives:setup.mode==='survival'?3:null,roundResolved:false,hintsUsed:0,wrong:0,revealed:0,revealOrder:[],attempts:0,current:null,blitzEnds:setup.mode==='blitz'?Date.now()+120000:null};show('universeGameScreen');applyTheme($('universeGameScreen'),setup.universe);await loadRound();startTicker();}catch(e){toast('Não consegui iniciar',e.message,'error');show('homeScreen')}}
  async function preload(url,ms=8000){return new Promise(r=>{const i=new Image();let done=false;const f=x=>{if(done)return;done=true;clearTimeout(t);i.onload=i.onerror=null;r(x)};const t=setTimeout(()=>f(false),ms);i.onload=()=>f(i.naturalWidth>60&&i.naturalHeight>60);i.onerror=()=>f(false);i.src=url})}
  async function loadRound(){if(!session)return;const mode=session.config.mode;if(mode==='survival'&&session.lives<=0)return endSession('lives');if(mode==='blitz'&&Date.now()>=session.blitzEnds)return endSession('blitz');if(session.index>=session.items.length || (mode==='classic'&&session.index>=20))return endSession('complete');let item=session.items[session.index];let tries=0;while(item&&tries<10&&!(await preload(item.image))){session.index++;item=session.items[session.index];tries++;}if(!item)return endSession('images');session.current=item;const diff=DIFF[session.config.difficulty];session.roundResolved=false;session.hintsUsed=0;session.wrong=0;session.revealed=0;session.attempts=diff.attempts;session.revealOrder=shuffle([0,1,2,3,4,5]);setupImage(item.image);for(let i=0;i<diff.pieces;i++)revealPiece();renderAttempts();renderHints();$('universeHintDisplay').innerHTML='<span class="hint-placeholder">💡 Use uma pista apenas quando precisar. Cada pista revela mais um fragmento.</span>';$('universeGuessInput').value='';$('universeSuggestions').classList.remove('active');updateUI();setTimeout(()=>$('universeGuessInput').focus(),50)}
  function setupImage(url){const g=$('universeImageGrid');g.innerHTML='';for(let i=0;i<6;i++){const row=Math.floor(i/3),col=i%3,p=document.createElement('div');p.className='image-piece universe-piece';p.id=`u-piece-${i}`;const img=document.createElement('img');img.src=url;img.alt='';img.style.cssText=`width:300%;height:200%;object-fit:cover;left:${-col*100}%;top:${-row*100}%;${session?.config?.universe==='pokemon'&&session?.config?.filter==='silhouette'?'filter:brightness(0);':''}`;p.appendChild(img);g.appendChild(p)}}
  function revealPiece(){if(!session||session.revealed>=6)return;const idx=session.revealOrder[session.revealed++];$(`u-piece-${idx}`)?.classList.add('revealed');$('universeImageStatus').textContent=`${session.revealed} fragmento${session.revealed===1?'':'s'} revelado${session.revealed===1?'':'s'}`;sound('reveal')}
  function renderAttempts(){const g=$('universeAttempts');g.innerHTML='';for(let i=0;i<DIFF[session.config.difficulty].attempts;i++){const d=document.createElement('i');d.className='attempt-dot '+(i<session.attempts?'left':'used');g.appendChild(d)}}
  function maskText(text,ratio){if(!ratio)return text;return String(text).split(/(\s+)/).map(w=>{if(w.trim().length<5||Math.random()>ratio)return w;return w[0]+'•'.repeat(Math.max(2,w.length-2))+w.at(-1)}).join('')}
  function renderHints(){const g=$('universeHintsContainer');g.innerHTML='';let clues=[...(session.current.clues||[])];if(session.config.difficulty==='insane')clues=clues.slice(0,3);shuffle(clues).forEach((c,i)=>{const b=document.createElement('button');b.className='hint-btn';b.innerHTML=`<span>${['🧩','🔎','📌','✨'][i%4]}</span>${esc(c.label.replace(/^\S+\s*/,''))}`;b.onclick=()=>{if(b.disabled||session.roundResolved)return;b.disabled=true;session.hintsUsed++;revealPiece();const ratio=DIFF[session.config.difficulty].mask;$('universeHintDisplay').className='hint-display active';$('universeHintDisplay').innerHTML=`<strong>${esc(c.label)}</strong>&nbsp; ${esc(maskText(c.text,ratio))}`;updateUI();sound('hint')};g.appendChild(b)})}
  function updateUI(){if(!session)return;const u=UNIVERSES[session.config.universe],d=DIFF[session.config.difficulty],m=MODES[session.config.mode];$('universeModeBadge').textContent=`${u.icon} ${m.title.toUpperCase()}`;$('universeSourceBadge').textContent=u.source;$('universeRoundMetric').textContent=`🎯 ${session.index+1} / ${session.config.mode==='classic'?20:'∞'}`;$('universeLivesMetric').classList.toggle('hidden',session.config.mode!=='survival');if(session.config.mode==='survival')$('universeLivesMetric').textContent='❤️'.repeat(session.lives)+'🖤'.repeat(3-session.lives);$('universeTimerMetric').classList.toggle('hidden',session.config.mode!=='blitz');$('universeScoreMetric').textContent=session.score;$('universeStreakMetric').textContent=`🔥 x${combo(session.streak)}`;$('universeComboChip').textContent=`🔥 COMBO x${combo(session.streak)}`;$('universeRoundEyebrow').textContent=u.eyebrow;$('universeRoundTitle').textContent=u.roundTitle||'Observe a imagem e arrisque';$('universeDifficultyLabel').textContent=d.title.toUpperCase();const val=roundValue();$('universeRoundValue').textContent=`+${val}`;renderAttempts()}
  function combo(s){return s>=10?3:s>=5?2:s>=3?1.5:1}
  function roundValue(){if(!session)return 0;const d=DIFF[session.config.difficulty];return Math.max(80,Math.round((600-session.hintsUsed*70-session.wrong*85)*d.mult*combo(session.streak)))}
  function answerNames(){const x=session.current;return [x.name,...(x.aliases||[])].map(norm).filter(Boolean)}
  function levenshtein(a,b){const m=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=m[0];m[0]=i;for(let j=1;j<=b.length;j++){const t=m[j];m[j]=Math.min(m[j]+1,m[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=t}}return m[b.length]}
  function isCorrect(v){const n=norm(v);if(!n)return false;return answerNames().some(a=>n===a||(Math.min(n.length,a.length)>=5&&1-levenshtein(n,a)/Math.max(n.length,a.length)>=.88))}
  function guess(){if(!session||session.roundResolved)return;const val=$('universeGuessInput').value.trim();if(!val)return;if(isCorrect(val))return win();session.wrong++;session.attempts--;revealPiece();renderAttempts();sound('error');$('universeHintDisplay').className='hint-display error';$('universeHintDisplay').innerHTML=`❌ <strong>${esc(val)}</strong> não é a resposta. Um novo fragmento foi revelado.`;if(session.attempts<=0)lose('tentativas');else updateUI()}
  function win(){if(session.roundResolved)return;session.roundResolved=true;const pts=roundValue();session.score+=pts;session.wins++;session.streak++;updateProfileWin(session.config.universe,pts,session.streak);for(let i=session.revealed;i<6;i++)revealPiece();sound('win');if(session.config.mode==='blitz'){toast('✅ Acertou!',`+${pts} pontos • ${session.current.name}`);session.index++;setTimeout(()=>loadRound(),420);return;}confetti();showResult(true,pts)}
  function lose(reason='pulo'){if(session.roundResolved)return;session.roundResolved=true;session.losses++;session.streak=0;if(session.config.mode==='survival')session.lives=Math.max(0,session.lives-1);updateProfileLoss();for(let i=session.revealed;i<6;i++)revealPiece();sound('lose');if(session.config.mode==='blitz'){toast('❌ Passou',`Era ${session.current.name}.`,'error');session.index++;setTimeout(()=>loadRound(),520);return;}showResult(false,0,reason)}
  function showResult(won,pts){const u=UNIVERSES[session.config.universe],x=session.current;$('universeResultModal').className='result-modal '+(won?'success':'fail');$('universeResultIcon').textContent=won?'✅':'❌';$('universeResultEyebrow').textContent=won?'VOCÊ ACERTOU!':'ERA ESTE:';$('universeResultName').textContent=x.name;$('universeResultImage').src=x.image;$('universeResultInfo').innerHTML=(x.result||[]).filter(Boolean).map(t=>`<div>${esc(t)}</div>`).join('')+`<div>🌌 ${esc(u.title)}</div>`;$('universeRewardLine').innerHTML=won?`⭐ <b>+${pts} pontos</b> • 🔥 sequência ${session.streak}`:`A sequência foi zerada.${session.config.mode==='survival'?` Restam <b>${session.lives}</b> vida(s).`:''}`;$('universeResultOverlay').classList.add('active');$('universeResultOverlay').setAttribute('aria-hidden','false');resultAction=()=>{closeResult();session.index++;loadRound()}}
  function closeResult(){$('universeResultOverlay').classList.remove('active');$('universeResultOverlay').setAttribute('aria-hidden','true')}
  function endSession(reason){stopTicker();if(!session)return;const s=session,u=UNIVERSES[s.config.universe];const p=readProfile();p.highScore=Math.max(Number(p.highScore||0),s.score);saveProfile(p);toast(reason==='images'?'Poucas imagens disponíveis':'Sessão encerrada',`${u.title}: ${s.wins} acertos • ${s.score} pontos.`);session=null;closeResult();show('homeScreen')}
  function startTicker(){stopTicker();ticker=setInterval(()=>{if(!session)return;if(session.config.mode==='blitz'){const left=Math.max(0,Math.ceil((session.blitzEnds-Date.now())/1000));$('universeTimerMetric').textContent=`⏱️ ${left}`;if(left<=0)endSession('blitz')}},250)}
  function stopTicker(){if(ticker){clearInterval(ticker);ticker=null}}
  function renderSuggestions(){const box=$('universeSuggestions'),n=norm($('universeGuessInput').value);box.innerHTML='';if(!session||n.length<2){box.classList.remove('active');return}const m=session.items.filter(x=>norm(x.name).includes(n)).slice(0,7);m.forEach(x=>{const d=document.createElement('div');d.className='suggestion-item';d.innerHTML=`<b>${esc(x.name)}</b><small>${esc(UNIVERSES[session.config.universe].title)}</small>`;d.onclick=()=>{$('universeGuessInput').value=x.name;box.classList.remove('active')};box.appendChild(d)});box.classList.toggle('active',m.length>0)}
  function quit(){loadingToken++;stopTicker();session=null;closeResult();show('homeScreen')}

  function bind(){renderCards();$('universeBackHome').onclick=()=>show('homeScreen');$('universeStartButton').onclick=start;$('universeGuessButton').onclick=guess;$('universeSkipButton').onclick=()=>lose('pulo');$('universeQuitButton').onclick=quit;$('universeGuessInput').addEventListener('keydown',e=>{if(e.key==='Enter')guess()});$('universeGuessInput').addEventListener('input',renderSuggestions);$('universeNextButton').onclick=()=>{if(resultAction){const f=resultAction;resultAction=null;f()}};$('universeResultClose').onclick=()=>{if(resultAction){const f=resultAction;resultAction=null;f()}else closeResult()};const old=$('brandButton').onclick;$('brandButton').onclick=(e)=>{if(session)return quit();old?.call($('brandButton'),e)};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
