(() => {
'use strict';
const $=id=>document.getElementById(id), CORE=()=>window.GameGuessCore, FB=()=>window.GameGuessFirebase;
const KEY='gameGuessArcadeV4';
const STARTER=['hair_basic','top_basic','bottom_basic','shoes_basic','acc_none','eye_round'];
const CATALOG=[
 {id:'hair_basic',slot:'hair',name:'Cabelo Casual',price:0,rarity:'Inicial',icon:'💇',style:'basic'},
 {id:'hair_spike',slot:'hair',name:'Cabelo Spike',price:35,rarity:'Comum',icon:'⚡',style:'spike'},
 {id:'hair_side',slot:'hair',name:'Franja Lateral',price:45,rarity:'Raro',icon:'🌊',style:'side'},
 {id:'hair_messy',slot:'hair',name:'Cabelo Rebelde',price:55,rarity:'Raro',icon:'🔥',style:'messy'},
 {id:'hair_bun',slot:'hair',name:'Coque Gamer',price:65,rarity:'Épico',icon:'🎀',style:'bun'},
 {id:'hair_mohawk',slot:'hair',name:'Mohawk Neon',price:80,rarity:'Épico',icon:'🌈',style:'mohawk'},
 {id:'eye_round',slot:'eyes',name:'Olhos Brilhantes',price:0,rarity:'Inicial',icon:'👁️',style:'round'},
 {id:'eye_star',slot:'eyes',name:'Olhos Estrela',price:40,rarity:'Raro',icon:'✨',style:'star'},
 {id:'eye_cyber',slot:'eyes',name:'Olhos Cyber',price:60,rarity:'Épico',icon:'🔷',style:'cyber'},
 {id:'top_basic',slot:'top',name:'Camiseta GG',price:0,rarity:'Inicial',icon:'👕',style:'tee'},
 {id:'top_hoodie',slot:'top',name:'Moletom Arcade',price:55,rarity:'Raro',icon:'🧥',style:'hoodie'},
 {id:'top_jacket',slot:'top',name:'Jaqueta Neon',price:75,rarity:'Épico',icon:'🧥',style:'jacket'},
 {id:'top_sport',slot:'top',name:'Camisa Esportiva',price:45,rarity:'Comum',icon:'🎽',style:'sport'},
 {id:'bottom_basic',slot:'bottom',name:'Calça Casual',price:0,rarity:'Inicial',icon:'👖',style:'pants'},
 {id:'bottom_short',slot:'bottom',name:'Short Street',price:35,rarity:'Comum',icon:'🩳',style:'short'},
 {id:'bottom_cargo',slot:'bottom',name:'Cargo Gamer',price:55,rarity:'Raro',icon:'👖',style:'cargo'},
 {id:'shoes_basic',slot:'shoes',name:'Tênis Básico',price:0,rarity:'Inicial',icon:'👟',style:'basic'},
 {id:'shoes_runner',slot:'shoes',name:'Tênis Runner',price:35,rarity:'Comum',icon:'👟',style:'runner'},
 {id:'shoes_neon',slot:'shoes',name:'Sneaker Neon',price:60,rarity:'Raro',icon:'👟',style:'neon'},
 {id:'acc_none',slot:'accessory',name:'Sem acessório',price:0,rarity:'Inicial',icon:'➖',style:'none'},
 {id:'acc_glasses',slot:'accessory',name:'Óculos Pixel',price:30,rarity:'Comum',icon:'🕶️',style:'glasses'},
 {id:'acc_headset',slot:'accessory',name:'Headset Pro',price:55,rarity:'Raro',icon:'🎧',style:'headset'},
 {id:'acc_cap',slot:'accessory',name:'Boné Street',price:45,rarity:'Comum',icon:'🧢',style:'cap'},
 {id:'acc_wings',slot:'accessory',name:'Asas Celestiais',price:90,rarity:'Épico',icon:'🪽',style:'wings'},
 {id:'acc_mask',slot:'accessory',name:'Máscara Tech',price:70,rarity:'Épico',icon:'🥷',style:'mask'}
];
const HAIR_COLORS=['#15151d','#4b2c22','#8b5a2b','#d5ad63','#d7d8dc','#e85b78','#7b5cff','#25b7d3','#31b66e','#cf4a35'];
const SKINS=['#f7d6be','#e9ba96','#d99a73','#b97852','#8d5438','#633822'];
const EYE_COLORS=['#1b1c28','#225fb7','#2f9f75','#6e43bd','#b86632','#d23f67'];
const CLOTH_COLORS=['#1c2438','#5d3fd3','#1875c9','#0a9c75','#bd3b5e','#e58a27','#e7e7ea','#222'];
function read(){try{return CORE()?.getProfile?.()||JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function write(p){CORE()?.replaceProfile?.(p);CORE()?.saveProfile?.();try{FB()?.syncLocalProfile?.(p)}catch{}}
function defaults(p={}){
 const owned=new Set([...(p.avatarOwned||[]),...STARTER]);
 return {...p,avatarOwned:[...owned],nickname:String(p.nickname||''),bio:String(p.bio||'Explorador, jogador e colecionador de desafios.'),favoriteGame:String(p.favoriteGame||'Game Guess'),avatar:{skin:'#f7d6be',hairColor:'#15151d',eyeColor:'#225fb7',clothColor:'#5d3fd3',hair:'hair_basic',eyes:'eye_round',top:'top_basic',bottom:'bottom_basic',shoes:'shoes_basic',accessory:'acc_none',...(p.avatar||{})}};
}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function item(id){return CATALOG.find(x=>x.id===id)||CATALOG[0]}
function svgAvatar(cfg={},size='large'){
 const c=defaults({avatar:cfg}).avatar, hair=item(c.hair).style,eyes=item(c.eyes).style,top=item(c.top).style,bottom=item(c.bottom).style,shoes=item(c.shoes).style,acc=item(c.accessory).style;
 const eyeShape=eyes==='cyber'?`<path d="M86 135h38l-6 22H92z" fill="${c.eyeColor}"/><path d="M156 135h38l-6 22h-26z" fill="${c.eyeColor}"/>`:eyes==='star'?`<text x="88" y="159" font-size="38" fill="${c.eyeColor}">★</text><text x="158" y="159" font-size="38" fill="${c.eyeColor}">★</text>`:`<ellipse cx="108" cy="145" rx="18" ry="23" fill="#fff"/><ellipse cx="172" cy="145" rx="18" ry="23" fill="#fff"/><ellipse cx="108" cy="149" rx="11" ry="15" fill="${c.eyeColor}"/><ellipse cx="172" cy="149" rx="11" ry="15" fill="${c.eyeColor}"/><circle cx="104" cy="143" r="4" fill="#fff"/><circle cx="168" cy="143" r="4" fill="#fff"/>`;
 const hairShapes={basic:`<path d="M70 110Q73 47 139 45q68 0 72 66-28-25-54-15-31-28-87 14z" fill="${c.hairColor}"/><path d="M77 95q25-52 61-30l-18 32-17-25-4 30z" fill="${c.hairColor}"/>`,spike:`<path d="M68 113L80 55l20 18 10-39 27 31 22-39 9 43 34-24-8 55q-52-26-126 13z" fill="${c.hairColor}"/>`,side:`<path d="M67 111q8-69 75-69 65 0 72 70-40-47-104-19-16 8-43 18z" fill="${c.hairColor}"/><path d="M78 83q64-45 120-13-48 7-72 45-24-26-48-32z" fill="${c.hairColor}"/>`,messy:`<path d="M67 111l8-55 20 14 14-35 22 26 24-34 12 37 33-20 6 67q-60-27-139 0z" fill="${c.hairColor}"/><path d="M81 84l22-42 9 37 32-51 3 54 37-40-13 53z" fill="${c.hairColor}"/>`,bun:`<circle cx="194" cy="58" r="29" fill="${c.hairColor}"/><path d="M69 111q8-66 72-66t70 67q-53-31-142-1z" fill="${c.hairColor}"/>`,mohawk:`<path d="M102 77l16-55 18 47 22-59 9 65 26-35-3 69q-44-28-88-2z" fill="${c.hairColor}"/>`};
 const topShape=top==='hoodie'?`<path d="M82 226q11-44 58-44t59 44v75H82z" fill="${c.clothColor}"/><path d="M103 188q36-29 74 1l-13 29h-49z" fill="#121827"/><path d="M125 220h30v9h-30z" fill="#fff" opacity=".8"/>`:top==='jacket'?`<path d="M83 226q12-43 57-43t58 43v75H83z" fill="${c.clothColor}"/><path d="M139 185v114" stroke="#e8f3ff" stroke-width="7"/><path d="M92 237h34M154 237h34" stroke="#0c1321" stroke-width="5"/>`:top==='sport'?`<path d="M84 226q10-43 56-43t57 43v74H84z" fill="${c.clothColor}"/><path d="M99 204l19 18 22-31 22 31 18-18" fill="none" stroke="#fff" stroke-width="7"/><text x="128" y="265" font-size="31" font-weight="900" fill="#fff">GG</text>`:`<path d="M84 226q11-43 56-43t57 43v74H84z" fill="${c.clothColor}"/><circle cx="140" cy="247" r="22" fill="#fff" opacity=".9"/><text x="129" y="258" font-size="28" font-weight="900" fill="#16203b">?</text>`;
 const bottomShape=bottom==='short'?`<path d="M99 291h82l-5 39h-29l-7-25-7 25h-29z" fill="#26415e"/>`:bottom==='cargo'?`<path d="M100 292h80l-5 63h-27l-8-45-8 45h-27z" fill="#263245"/><rect x="102" y="309" width="22" height="18" rx="4" fill="#3f5068"/><rect x="156" y="309" width="22" height="18" rx="4" fill="#3f5068"/>`:`<path d="M100 292h80l-5 63h-27l-8-45-8 45h-27z" fill="#243b65"/>`;
 const shoeColor=shoes==='neon'?'#8b5cff':shoes==='runner'?'#e7edf8':'#171a23';
 const accShape=acc==='glasses'?`<g fill="none" stroke="#d9e7ff" stroke-width="5"><rect x="85" y="132" width="42" height="29" rx="10"/><rect x="153" y="132" width="42" height="29" rx="10"/><path d="M127 144h26"/></g>`:acc==='headset'?`<path d="M76 145q0-68 64-68t64 68" fill="none" stroke="#8c5cff" stroke-width="10"/><rect x="70" y="139" width="18" height="45" rx="8" fill="#252a3b"/><rect x="192" y="139" width="18" height="45" rx="8" fill="#252a3b"/>`:acc==='cap'?`<path d="M73 93q16-50 69-50 52 0 65 50-80-21-134 0z" fill="#305cc8"/><path d="M139 90q51-13 83 1-29 18-70 13z" fill="#234495"/>`:acc==='wings'?`<path d="M83 224Q22 190 28 260q23-22 58-9M197 224q61-34 55 36-23-22-58-9" fill="#e8f7ff" stroke="#a9d8ff" stroke-width="4"/>`:acc==='mask'?`<path d="M102 166q38 18 76 0v27q-38 25-76 0z" fill="#192032"/><path d="M117 176h46" stroke="#58e8ff" stroke-width="4"/>`:'';
 return `<svg class="gg-avatar-svg ${size}" viewBox="0 0 280 380" role="img" aria-label="Avatar personalizado"><defs><radialGradient id="skinGlow"><stop stop-color="#fff" stop-opacity=".32"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient><filter id="avShadow"><feDropShadow dx="0" dy="8" stdDeviation="8" flood-opacity=".35"/></filter></defs><ellipse cx="140" cy="363" rx="75" ry="12" fill="#000" opacity=".28"/><g filter="url(#avShadow)">${acc==='wings'?accShape:''}${bottomShape}<rect x="108" y="326" width="25" height="31" rx="9" fill="${c.skin}"/><rect x="148" y="326" width="25" height="31" rx="9" fill="${c.skin}"/><path d="M96 350h42v20H94q-9-2 2-20z" fill="${shoeColor}"/><path d="M143 350h43q10 17-2 20h-43z" fill="${shoeColor}"/>${topShape}<ellipse cx="78" cy="242" rx="18" ry="45" fill="${c.skin}" transform="rotate(8 78 242)"/><ellipse cx="202" cy="242" rx="18" ry="45" fill="${c.skin}" transform="rotate(-8 202 242)"/><ellipse cx="140" cy="137" rx="79" ry="84" fill="${c.skin}"/><ellipse cx="140" cy="120" rx="55" ry="42" fill="url(#skinGlow)"/>${eyeShape}<path d="M129 181q11 10 22 0" fill="none" stroke="#8b4f47" stroke-width="4" stroke-linecap="round"/>${hairShapes[hair]||hairShapes.basic}${acc!=='wings'?accShape:''}</g></svg>`;
}

let avatar3D=null;
function dispose3D(){if(!avatar3D)return;try{avatar3D.renderer?.dispose?.();avatar3D.host?.replaceChildren();}catch{}avatar3D=null;}
function renderAvatar3D(cfg={}){
  const host=$('avatarPreview');if(!host||!window.THREE){if(host)host.innerHTML=svgAvatar(cfg);return;}
  const THREE=window.THREE,c=defaults({avatar:cfg}).avatar;
  if(!avatar3D){
    host.innerHTML='';const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(2,window.devicePixelRatio||1));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);
    const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(28,1,.1,100);camera.position.set(0,1.2,9.3);camera.lookAt(0,.7,0);const amb=new THREE.HemisphereLight(0xcbeaff,0x20172d,2.15);scene.add(amb);const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(4,7,7);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x7b5cff,2.5);rim.position.set(-5,3,-3);scene.add(rim);const group=new THREE.Group();scene.add(group);
    const resize=()=>{const r=host.getBoundingClientRect(),w=Math.max(260,r.width),h=Math.max(400,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(host);let dragging=false,lastX=0,targetY=0;renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;targetY+=(e.clientX-lastX)*.012;lastX=e.clientX});renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('pointercancel',()=>dragging=false);
    const animate=()=>{if(!avatar3D)return;group.rotation.y+=(targetY-group.rotation.y)*.08;group.position.y=Math.sin(performance.now()/900)*.035;renderer.render(scene,camera);avatar3D.raf=requestAnimationFrame(animate)};avatar3D={host,renderer,scene,camera,group,ro,raf:0};animate();
  }
  const g=avatar3D.group;while(g.children.length){const o=g.children.pop();o.traverse?.(n=>{n.geometry?.dispose?.();if(n.material){const ms=Array.isArray(n.material)?n.material:[n.material];ms.forEach(m=>m.dispose?.())}})}
  const mat=(color,rough=.62,metal=.04)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});const skin=mat(c.skin,.7),hairMat=mat(c.hairColor,.78),cloth=mat(c.clothColor,.6),dark=mat('#171d2d',.72),white=mat('#f7fbff',.5),eye=mat(c.eyeColor,.3,.08),shoe=mat(item(c.shoes).style==='neon'?'#7958ff':item(c.shoes).style==='runner'?'#e6edf8':'#151923',.45);
  const add=(geo,m,x,y,z,sx=1,sy=1,sz=1,rx=0,ry=0,rz=0)=>{const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.rotation.set(rx,ry,rz);o.castShadow=true;o.receiveShadow=true;g.add(o);return o};
  // legs + shoes
  add(new THREE.CylinderGeometry(.24,.28,1.1,20),dark,-.35,-1.42,0,.9,1,1);add(new THREE.CylinderGeometry(.24,.28,1.1,20),dark,.35,-1.42,0,.9,1,1);add(new THREE.BoxGeometry(.7,.34,1.05),shoe,-.35,-2.05,.24,1,1,1);add(new THREE.BoxGeometry(.7,.34,1.05),shoe,.35,-2.05,.24,1,1,1);
  // body
  const topStyle=item(c.top).style;add(new THREE.CylinderGeometry(.78,.66,1.35,28),cloth,0,-.45,0,1,1,1);if(topStyle==='jacket'){add(new THREE.BoxGeometry(.06,1.18,.06),white,0,-.42,.67)}if(topStyle==='hoodie'){add(new THREE.TorusGeometry(.57,.12,10,28,Math.PI),dark,0,.2,-.2,1,1,1,Math.PI/2,0,0)}if(topStyle==='sport'){const badge=add(new THREE.CylinderGeometry(.24,.24,.035,24),white,0,-.36,.68,1,1,1,Math.PI/2);badge.rotation.x=Math.PI/2;}
  // arms
  add(new THREE.CylinderGeometry(.18,.22,1.18,18),cloth,-.88,-.48,0,1,1,1,0,0,-.14);add(new THREE.CylinderGeometry(.18,.22,1.18,18),cloth,.88,-.48,0,1,1,1,0,0,.14);add(new THREE.SphereGeometry(.22,18,18),skin,-.96,-1.05,.02);add(new THREE.SphereGeometry(.22,18,18),skin,.96,-1.05,.02);
  // head and ears
  add(new THREE.SphereGeometry(1.2,40,32),skin,0,1.02,.02,1,1.08,.96);add(new THREE.SphereGeometry(.21,20,16),skin,-1.15,1.0,0);add(new THREE.SphereGeometry(.21,20,16),skin,1.15,1.0,0);
  // eyes
  const eyeStyle=item(c.eyes).style;if(eyeStyle==='cyber'){add(new THREE.BoxGeometry(.58,.31,.09),eye,-.43,1.08,1.0,1,1,1);add(new THREE.BoxGeometry(.58,.31,.09),eye,.43,1.08,1.0)}else{add(new THREE.SphereGeometry(.27,24,20),white,-.43,1.08,1.0,1,.92,.35);add(new THREE.SphereGeometry(.27,24,20),white,.43,1.08,1.0,1,.92,.35);add(new THREE.SphereGeometry(.17,22,18),eye,-.43,1.06,1.19,1,1,.32);add(new THREE.SphereGeometry(.17,22,18),eye,.43,1.06,1.19,1,1,.32);add(new THREE.SphereGeometry(.055,12,10),white,-.48,1.14,1.25);add(new THREE.SphereGeometry(.055,12,10),white,.38,1.14,1.25);if(eyeStyle==='star'){for(const x of [-.43,.43]){const star=add(new THREE.OctahedronGeometry(.075,0),white,x,1.07,1.33);star.rotation.z=.5}}}
  // mouth
  const mouth=new THREE.Mesh(new THREE.TorusGeometry(.17,.024,8,24,Math.PI),mat('#8e4b53',.65));mouth.position.set(0,.63,1.12);mouth.rotation.z=Math.PI;g.add(mouth);
  // hair cap + styles
  const hstyle=item(c.hair).style;add(new THREE.SphereGeometry(1.24,32,24,0,Math.PI*2,0,Math.PI*.48),hairMat,0,1.45,-.06,1,1,.97);const cone=new THREE.ConeGeometry(.23,.72,12);const spike=(x,y,z,rz=0,s=.9)=>add(cone,hairMat,x,y,z,s,s,s,0,0,rz);
  if(['spike','messy','mohawk'].includes(hstyle)){const count=hstyle==='mohawk'?5:9;for(let i=0;i<count;i++){const a=(i/(count-1)-.5)*(hstyle==='mohawk'?1.25:2.0),x=hstyle==='mohawk'?a*.25:a*.82,y=2.18-Math.abs(a)*.15,z=hstyle==='mohawk'?.0:.05;spike(x,y,z,-a*.28,hstyle==='messy'?1:1.05)}}
  if(hstyle==='side'){for(let i=0;i<4;i++)spike(-.72+i*.28,1.88,1.0,-.55+i*.13,.78)}if(hstyle==='bun')add(new THREE.SphereGeometry(.42,24,20),hairMat,.82,2.08,-.18);if(hstyle==='basic'){for(let i=0;i<4;i++)spike(-.5+i*.32,1.88,1.0,-.35+i*.18,.7)}
  // accessories
  const acc=item(c.accessory).style;if(acc==='glasses'){const tor=new THREE.TorusGeometry(.35,.035,10,32);add(tor,dark,-.43,1.08,1.28,1,1,.28);add(tor,dark,.43,1.08,1.28,1,1,.28);add(new THREE.BoxGeometry(.25,.04,.04),dark,0,1.08,1.3)}else if(acc==='headset'){add(new THREE.TorusGeometry(1.28,.09,10,40,Math.PI),mat('#765cff',.35,.2),0,1.22,-.05,1,1,1,0,0,0);add(new THREE.BoxGeometry(.24,.65,.32),dark,-1.2,1.1,.03);add(new THREE.BoxGeometry(.24,.65,.32),dark,1.2,1.1,.03)}else if(acc==='cap'){add(new THREE.SphereGeometry(1.25,28,16,0,Math.PI*2,0,Math.PI*.3),mat('#315fc9',.65),0,1.65,.02,1,1,.98);add(new THREE.BoxGeometry(1.1,.08,.48),mat('#254797',.65),.35,1.72,1.0,1,1,1,0,.15,0)}else if(acc==='wings'){for(const x of [-1,1]){const wing=add(new THREE.SphereGeometry(.75,18,14),white,x*1.05,-.25,-.55,.55,1.15,.18,0,0,x*.28);wing.material.transparent=true;wing.material.opacity=.9}}else if(acc==='mask'){add(new THREE.BoxGeometry(.85,.38,.12),dark,0,.66,1.05,1,1,1,.1);add(new THREE.BoxGeometry(.6,.04,.04),mat('#5de8ff',.25,.25),0,.69,1.14)}
  g.rotation.y=0;
}

function inject(){
 const main=document.querySelector('main.shell');if(!main||$('profileScreen'))return;
 const top=document.querySelector('.top-actions');if(top){const b=document.createElement('button');b.className='mini-pill';b.id='profileButton';b.title='Meu perfil';b.innerHTML='🧑 <b>Perfil</b>';top.insertBefore(b,$('achievementsButton'));const a=document.createElement('button');a.className='mini-pill';a.id='avatarButton';a.title='Avatar e loja';a.innerHTML='✨ <b>Avatar</b>';top.insertBefore(a,b);}
 const home=$('homeScreen');if(home){const banner=document.createElement('section');banner.className='social-home-banner';banner.innerHTML=`<div class="social-home-avatar" id="homeAvatarPreview"></div><div><p class="eyebrow">👤 SEU JOGADOR</p><h2>Perfil, avatar e coleção</h2><p>Monte seu visual, desbloqueie itens e acompanhe suas estatísticas em um perfil próprio.</p></div><div class="social-home-actions"><button class="primary-btn" id="homeProfileButton">ABRIR PERFIL</button><button class="secondary-btn" id="homeAvatarButton">PERSONALIZAR AVATAR</button></div>`;const q=home.querySelector('.quiz-home-banner');home.insertBefore(banner,q||home.firstChild);}
 main.insertAdjacentHTML('beforeend',`<section class="screen profile-screen" id="profileScreen"><div class="section-heading"><button class="back-link" id="profileBack">← Voltar</button><div><p class="eyebrow">👤 PERFIL DO JOGADOR</p><h2>Seu espaço no Game Guess</h2><p>Visual, recordes e identidade da sua conta.</p></div></div><div class="profile-v15-layout"><section class="profile-v15-hero"><div id="profileAvatarHero" class="profile-avatar-hero"></div><div class="profile-v15-id"><span class="online-dot">● ONLINE</span><h2 id="profileNickLabel">Jogador</h2><p id="profileBioLabel"></p><div class="profile-favorite">🎮 Favorito: <b id="profileFavLabel">Game Guess</b></div><button class="secondary-btn" id="profileEditAvatar">✨ Editar avatar</button></div></section><section class="profile-edit-card"><h3>✏️ Identidade</h3><label>Nickname<input id="profileNickInput" maxlength="22" placeholder="Seu nickname"></label><label>Bio<textarea id="profileBioInput" maxlength="120"></textarea></label><label>Jogo favorito<select id="profileFavoriteInput"><option>Game Guess</option><option>GeoGuess Arena</option><option>Quiz Mundial</option><option>Termo Arcade</option><option>KOF 2002 Magic Plus II</option><option>Multiverso</option><option>Arena Online</option></select></label><button class="primary-btn" id="profileSave">SALVAR PERFIL</button></section><section class="profile-stat-grid" id="profileStatGrid"></section><section class="profile-showcase"><div><h3>🏆 Destaques</h3><div id="profileHighlights" class="profile-highlight-grid"></div></div><div><h3>🎒 Visual equipado</h3><div id="profileEquipped" class="profile-equipped"></div></div></section></div></section>
 <section class="screen avatar-screen" id="avatarScreen"><div class="section-heading"><button class="back-link" id="avatarBack">← Voltar</button><div><p class="eyebrow">✨ AVATAR</p><h2>Crie seu personagem</h2><p>Personalize rosto, cabelo, roupas, cores e acessórios.</p></div><div class="avatar-wallet">⭐ <b id="avatarCoins">0</b> pontos</div></div><div class="avatar-v15-layout"><section class="avatar-studio"><div class="avatar-preview-stage"><div id="avatarPreview"></div></div><div class="avatar-color-panel"><h3>Cores</h3><div><b>Pele</b><div id="skinSwatches" class="avatar-swatches"></div></div><div><b>Cabelo</b><div id="hairSwatches" class="avatar-swatches"></div></div><div><b>Olhos</b><div id="eyeSwatches" class="avatar-swatches"></div></div><div><b>Roupa</b><div id="clothSwatches" class="avatar-swatches"></div></div><button class="primary-btn" id="avatarSave">✓ SALVAR AVATAR</button><button class="secondary-btn" id="avatarRandom">🎲 ALEATÓRIO</button></div></section><section class="avatar-shop"><div class="avatar-shop-head"><div><p class="eyebrow">🛍️ LOJA</p><h2>Personalização</h2></div><div class="avatar-wallet">⭐ <b id="shopCoins">0</b></div></div><div class="shop-tabs" id="shopTabs"></div><div class="shop-grid" id="shopGrid"></div></section></div></section>`);
}
let shopSlot='hair';
function renderSwatches(id,vals,key,p){const el=$(id);if(!el)return;el.innerHTML=vals.map(v=>`<button class="avatar-swatch${p.avatar[key]===v?' active':''}" data-color-key="${key}" data-color="${v}" style="--sw:${v}" aria-label="${v}"></button>`).join('');}
function renderShop(p){const tabs=$('shopTabs');if(tabs)tabs.innerHTML=[['hair','Cabelo'],['eyes','Olhos'],['top','Roupas'],['bottom','Calças'],['shoes','Calçados'],['accessory','Acessórios']].map(([k,n])=>`<button class="${shopSlot===k?'active':''}" data-shop-slot="${k}">${n}</button>`).join('');const owned=new Set(p.avatarOwned||[]),grid=$('shopGrid');if(grid)grid.innerHTML=CATALOG.filter(x=>x.slot===shopSlot).map(x=>{const eq=p.avatar[shopSlot=== 'accessory'?'accessory':shopSlot]===x.id;return `<article class="shop-item ${eq?'equipped':''}"><div class="shop-item-icon">${x.icon}</div><div><b>${esc(x.name)}</b><small>${x.rarity}</small></div><button data-shop-item="${x.id}" ${eq?'disabled':''}>${eq?'EQUIPADO':owned.has(x.id)?'EQUIPAR':`⭐ ${x.price}`}</button></article>`}).join('');}
function stats(p){const played=Number(p.gamesPlayed||0),wins=Number(p.gamesWon||0);return [['⭐','Pontos',p.coins||0],['🏆','Maior pontuação',p.highScore||0],['🔥','Melhor sequência',p.bestStreak||0],['🎮','Partidas',played],['✅','Vitórias',wins],['🎯','Aproveitamento',played?`${Math.round(wins/played*100)}%`:'0%'],['⚔️','Vitórias Arena',p.duelWins||0],['🌍','GeoGuess vitórias',p.geoWins||0]];}
function renderProfile(){const p=defaults(read()),u=FB()?.getUser?.();$('profileAvatarHero').innerHTML=svgAvatar(p.avatar);$('profileNickLabel').textContent=p.nickname||u?.displayName||u?.email?.split('@')[0]||'Jogador';$('profileBioLabel').textContent=p.bio;$('profileFavLabel').textContent=p.favoriteGame;$('profileNickInput').value=p.nickname||'';$('profileBioInput').value=p.bio;$('profileFavoriteInput').value=p.favoriteGame;$('profileStatGrid').innerHTML=stats(p).map(([i,l,v])=>`<div><span>${i}</span><small>${l}</small><b>${v}</b></div>`).join('');const level=Math.max(1,Math.floor((Number(p.gamesPlayed||0)+Number(p.gamesWon||0)*2)/10)+1);$('profileHighlights').innerHTML=`<div>🎖️ <b>Nível ${level}</b><span>Experiência geral</span></div><div>🌟 <b>${(p.avatarOwned||[]).length}</b><span>Itens desbloqueados</span></div><div>🧠 <b>${p.termBestStreak||p.bestStreak||0}</b><span>Sequência destaque</span></div><div>🥊 <b>${p.kofRating||1000}</b><span>Elo KOF</span></div>`;$('profileEquipped').innerHTML=['hair','eyes','top','bottom','shoes','accessory'].map(k=>{const it=item(p.avatar[k]);return `<span title="${esc(it.name)}">${it.icon}<small>${esc(it.name)}</small></span>`}).join('');}
function renderAvatar(){const p=defaults(read());renderAvatar3D(p.avatar);$('avatarCoins').textContent=p.coins||0;$('shopCoins').textContent=p.coins||0;renderSwatches('skinSwatches',SKINS,'skin',p);renderSwatches('hairSwatches',HAIR_COLORS,'hairColor',p);renderSwatches('eyeSwatches',EYE_COLORS,'eyeColor',p);renderSwatches('clothSwatches',CLOTH_COLORS,'clothColor',p);renderShop(p);const h=$('homeAvatarPreview');if(h)h.innerHTML=svgAvatar(p.avatar,'mini');}
function setAvatarValue(key,val){const p=defaults(read());p.avatar[key]=val;write(p);renderAvatar();}
function buyEquip(id){const it=item(id),p=defaults(read()),owned=new Set(p.avatarOwned||[]);if(!owned.has(id)){if(Number(p.coins||0)<it.price)return CORE()?.toast?.('Pontos insuficientes',`Você precisa de ${it.price} pontos para ${it.name}.`,'error');p.coins=Math.max(0,Number(p.coins||0)-it.price);p.avatarSpent=Number(p.avatarSpent||0)+it.price;owned.add(id);p.avatarOwned=[...owned];CORE()?.playSound?.('coin');}p.avatar[it.slot]=it.id;write(p);renderAvatar();CORE()?.toast?.('Visual atualizado',`${it.name} equipado.`);}
function openProfile(){CORE()?.showScreen?.('profileScreen');renderProfile()}
function openAvatar(){CORE()?.showScreen?.('avatarScreen');renderAvatar()}
function bind(){inject();renderAvatar();$('profileButton')?.addEventListener('click',openProfile);$('avatarButton')?.addEventListener('click',openAvatar);$('homeProfileButton')?.addEventListener('click',openProfile);$('homeAvatarButton')?.addEventListener('click',openAvatar);$('profileBack')?.addEventListener('click',()=>CORE()?.showScreen?.('homeScreen'));$('avatarBack')?.addEventListener('click',()=>CORE()?.showScreen?.('homeScreen'));$('profileEditAvatar')?.addEventListener('click',openAvatar);$('profileSave')?.addEventListener('click',()=>{const p=defaults(read());p.nickname=String($('profileNickInput').value||'').trim().slice(0,22);p.bio=String($('profileBioInput').value||'').trim().slice(0,120);p.favoriteGame=$('profileFavoriteInput').value;write(p);renderProfile();CORE()?.toast?.('Perfil salvo','Suas alterações foram sincronizadas.');});$('avatarScreen')?.addEventListener('click',e=>{const sw=e.target.closest('[data-color-key]');if(sw)return setAvatarValue(sw.dataset.colorKey,sw.dataset.color);const tab=e.target.closest('[data-shop-slot]');if(tab){shopSlot=tab.dataset.shopSlot;return renderAvatar()}const it=e.target.closest('[data-shop-item]');if(it)return buyEquip(it.dataset.shopItem);});$('avatarSave')?.addEventListener('click',()=>{write(defaults(read()));CORE()?.toast?.('Avatar salvo','Seu novo visual foi salvo na conta.');});$('avatarRandom')?.addEventListener('click',()=>{const p=defaults(read()),owned=CATALOG.filter(x=>(p.avatarOwned||[]).includes(x.id));for(const slot of ['hair','eyes','top','bottom','shoes','accessory']){const pool=owned.filter(x=>x.slot===slot);if(pool.length)p.avatar[slot]=pool[Math.floor(Math.random()*pool.length)].id;}p.avatar.skin=SKINS[Math.floor(Math.random()*SKINS.length)];p.avatar.hairColor=HAIR_COLORS[Math.floor(Math.random()*HAIR_COLORS.length)];p.avatar.eyeColor=EYE_COLORS[Math.floor(Math.random()*EYE_COLORS.length)];p.avatar.clothColor=CLOTH_COLORS[Math.floor(Math.random()*CLOTH_COLORS.length)];write(p);renderAvatar();});window.addEventListener('gameguess:authchange',()=>{renderAvatar();if($('profileScreen')?.classList.contains('active'))renderProfile()});}
window.GameGuessSocial={openProfile,openAvatar,renderAvatar,svgAvatar};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
