(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const CORE=()=>window.GameGuessCore;
  const PROFILE_KEY='gameGuessArcadeV4';
  const RAW_WORDS=`amigo andar areia arroz aviao balde barco beber beijo bolsa brasa breve briga brisa broto cabra caixa calor campo canto carne carro carta casco causa chave chuva claro clube cobra coisa comer conta corpo corte crime culpa danca dever disco festa fibra filme final firma folha forte fraco frase fruta garfo gente globo golpe grama grupo hotel idade ideal igual jovem juros lagoa largo laser lavar leite lento livro lugar magia maior malha massa metal metro milho minha monte motor mundo navio negro nivel noite norma norte nuvem oeste olhar ordem outro papel parte passo peixe pedra peito perda perna piano pista plano ponto porta praia prazo preco preto prova queda reino renda ritmo roupa saber sabor salto senha sinal sonho sorte tarde tempo tenis terra tigre tocar torre total trigo turma valor verde vidro vinho volta zebra agile alado altar aluno amora anexo animo apito arame arcar aroma autor aviso balao banco barba bicho bloco boda? bolas bomba borda botao bravo busca caber cacau cacho cair? canoa capa? cargo casal censo cerco cheio chino? choro cifra cinco cinto civil clima copo? couro cravo credo cruel cunha dados dente digno drama duelo duplo enche exato falar falta farol feira feliz ferir festa ficha firme fiscal foco? fogo? forno fosso freio fugir fuzil garra gasto geral girar globo goela gosto grave grito honra hum? humor icone ideia? imune janta jogar lapis lebre legal lenda linha lista lunar macro manga marco maria? medio menor mente mesa? minar moral morro musica naipe nervo ninho nobre onda? opaco osso? pacto padre paiol palco pardo pausa pegar peito perto pinga pires poder polvo pomar ponte praia prato preso prima primo pulso radar raiva regra rival sabao sacar sagaz sala? salsa santo saude selva senso serra signo sitio sobra solar sonar suado subir sujar super surdo talho tanto tecla termo terno texto tinta titulo? tocha trigo troco trova urina? vagao vapor velar velho vento verba verso viagem? vigor viral viver vocal zelar zumbi`.split(/\s+/);
  function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z]/g,'');}
  const SOLUTIONS=[...new Set(RAW_WORDS.map(w=>w.replace('?','')).filter(w=>norm(w).length===5))];
  let state={target:'',guesses:[],current:'',ended:false,won:false,sessionScore:0,lastResult:[]};
  const KEY_ROWS=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];
  const rank={absent:1,present:2,correct:3};
  function readProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
  function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p));CORE()?.syncProfile?.();}
  function unlock(p,id,title,reward){p.achievements={...(p.achievements||{})};if(p.achievements[id])return;p.achievements[id]=Date.now();p.coins=Number(p.coins||0)+reward;CORE()?.toast?.('Conquista desbloqueada!',`${title} • +${reward} moedas`,'achievement');CORE()?.playSound?.('achievement');}
  function pickTarget(){const p=readProfile(),recent=Array.isArray(p.termRecent)?p.termRecent:[];let pool=SOLUTIONS.filter(w=>!recent.includes(norm(w)));if(!pool.length)pool=SOLUTIONS;const target=pool[Math.floor(Math.random()*pool.length)]||'termo';p.termRecent=[norm(target),...recent.filter(x=>x!==norm(target))].slice(0,35);saveProfile(p);return target;}
  function evaluate(guess,target){const g=[...norm(guess)],t=[...norm(target)],status=Array(5).fill('absent'),counts={};for(let i=0;i<5;i++){if(g[i]===t[i])status[i]='correct';else counts[t[i]]=(counts[t[i]]||0)+1;}for(let i=0;i<5;i++){if(status[i]==='correct')continue;if(counts[g[i]]>0){status[i]='present';counts[g[i]]--;}}return status;}
  function renderBoard(){const board=$('termoBoard');if(!board)return;board.innerHTML='';for(let r=0;r<6;r++){const row=document.createElement('div');row.className='termo-row';let letters='',statuses=[];if(state.guesses[r]){letters=norm(state.guesses[r]).toUpperCase();statuses=evaluate(state.guesses[r],state.target);}else if(r===state.guesses.length&&!state.ended){letters=norm(state.current).toUpperCase();}for(let c=0;c<5;c++){const tile=document.createElement('div');tile.className='termo-tile'+(statuses[c]?` ${statuses[c]}`:'')+(letters[c]?' filled':'');tile.textContent=letters[c]||'';if(statuses[c])tile.style.setProperty('--delay',`${c*70}ms`);row.appendChild(tile);}board.appendChild(row);}}
  function keyStates(){const map={};state.guesses.forEach(g=>{const st=evaluate(g,state.target),letters=[...norm(g).toUpperCase()];letters.forEach((l,i)=>{const x=st[i];if(!map[l]||rank[x]>rank[map[l]])map[l]=x;});});return map;}
  function renderKeyboard(){const box=$('termoKeyboard');if(!box)return;const states=keyStates();box.innerHTML='';KEY_ROWS.forEach((letters,idx)=>{const row=document.createElement('div');row.className='termo-key-row';if(idx===2){const enter=document.createElement('button');enter.className='termo-key wide';enter.textContent='ENTER';enter.onclick=()=>handle('ENTER');row.appendChild(enter);}for(const l of letters){const b=document.createElement('button');b.className='termo-key'+(states[l]?` ${states[l]}`:'');b.textContent=l;b.onclick=()=>handle(l);row.appendChild(b);}if(idx===2){const back=document.createElement('button');back.className='termo-key wide';back.textContent='⌫';back.onclick=()=>handle('BACKSPACE');row.appendChild(back);}box.appendChild(row);});}
  function renderStats(){const p=readProfile();const played=Number(p.termPlayed||0),wins=Number(p.termWins||0),best=Number(p.termBestStreak||0),streak=Number(p.termCurrentStreak||0);$('termoWins').textContent=wins;$('termoStreak').textContent=streak;$('termoBest').textContent=best;$('termoScore').textContent=state.sessionScore;$('termoPlayed').textContent=played;$('termoRate').textContent=played?`${Math.round(wins/played*100)}%`:'0%';$('termoSideBest').textContent=best;}
  function render(){renderBoard();renderKeyboard();renderStats();$('termoNextButton').classList.toggle('hidden',!state.ended);}
  function message(text,type=''){$('termoMessage').className='termo-message'+(type?` ${type}`:'');$('termoMessage').textContent=text;}
  function newRound(){state.target=pickTarget();state.guesses=[];state.current='';state.ended=false;state.won=false;state.lastResult=[];message('Digite uma palavra de 5 letras.');render();setTimeout(()=>window.focus(),20);}
  function endRound(won){state.ended=true;state.won=won;const p=readProfile();p.termPlayed=Number(p.termPlayed||0)+1;p.termWins=Number(p.termWins||0)+(won?1:0);p.termCurrentStreak=won?Number(p.termCurrentStreak||0)+1:0;p.termBestStreak=Math.max(Number(p.termBestStreak||0),Number(p.termCurrentStreak||0));let pts=0;if(won){pts=Math.max(40,170-(state.guesses.length-1)*22);state.sessionScore+=pts;p.coins=Number(p.coins||0)+Math.max(5,Math.round(pts/17));p.highScore=Math.max(Number(p.highScore||0),state.sessionScore);CORE()?.playSound?.('win');CORE()?.spawnConfetti?.();message(`✅ Acertou! ${state.target.toUpperCase()} • +${pts} pontos`,'success');}else{CORE()?.playSound?.('lose');message(`❌ A palavra era ${state.target.toUpperCase()}. A sequência foi zerada.`,'error');}if(Number(p.termWins||0)>=10)unlock(p,'wordsmith','🔤 Mestre das Palavras',140);if(Number(p.termBestStreak||0)>=5)unlock(p,'termoStreak','♾️ Sequência Infinita',190);saveProfile(p);render();}
  function submit(){if(state.current.length!==5){message('A tentativa precisa ter exatamente 5 letras.','error');CORE()?.playSound?.('error');return;}const guess=norm(state.current);state.guesses.push(guess);state.lastResult=evaluate(guess,state.target);state.current='';if(guess===norm(state.target))endRound(true);else if(state.guesses.length>=6)endRound(false);else{message(`Tentativa ${state.guesses.length}/6. Continue.`);CORE()?.playSound?.('hint');render();}}
  function handle(k){if(state.ended)return;if(k==='ENTER')return submit();if(k==='BACKSPACE'){state.current=state.current.slice(0,-1);return renderBoard();}const l=norm(k).toUpperCase();if(/^[A-Z]$/.test(l)&&state.current.length<5){state.current+=l;renderBoard();}}
  function share(){if(!state.guesses.length){CORE()?.toast?.('Termo Arcade','Jogue ao menos uma tentativa antes de compartilhar.');return;}const lines=state.guesses.map(g=>evaluate(g,state.target).map(x=>x==='correct'?'🟩':x==='present'?'🟨':'⬛').join('')).join('\n');const text=`🔤 TERMO ARCADE ∞\n${state.won?state.guesses.length:'X'}/6\n${lines}\n🔥 sequência ${Number(readProfile().termCurrentStreak||0)}`;if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>CORE()?.toast?.('Copiado','Resultado do Termo Arcade copiado.'));}
  function open(){CORE()?.showScreen?.('termoScreen');if(!state.target||state.ended)newRound();else render();}
  function resetStreak(){const p=readProfile();p.termCurrentStreak=0;saveProfile(p);state.sessionScore=0;message('Sequência reiniciada. A palavra atual continua valendo.');renderStats();}
  function bind(){if(!$('termoScreen'))return;$('termoQuitButton').onclick=()=>CORE()?.showScreen?.('homeScreen');$('termoNextButton').onclick=newRound;$('termoShareButton').onclick=share;$('termoResetButton').onclick=resetStreak;window.addEventListener('keydown',e=>{if(!$('termoScreen').classList.contains('active'))return;if(e.key==='Enter'){e.preventDefault();handle('ENTER');}else if(e.key==='Backspace'){e.preventDefault();handle('BACKSPACE');}else if(/^[a-zA-ZÀ-ÿ]$/.test(e.key)){handle(e.key);}});renderStats();}
  window.GameGuessTermo={open};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
