function j(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(body));}
async function fetchBin(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{return await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'GameGuess-V6/1.0','Accept':'image/avif,image/webp,image/*,*/*;q=.8'}})}finally{clearTimeout(t)}}
function safeId(s){return /^[A-Za-z0-9_.-]{1,100}$/.test(String(s||''))?String(s):''}
function allowedDigi(raw){try{const u=new URL(raw);return ['digi-api.com','www.digi-api.com'].includes(u.hostname)?u.toString():''}catch{return ''}}
async function wikiThumb(title){for(const lang of ['pt','en']){const q=new URL(`https://${lang}.wikipedia.org/w/api.php`);q.searchParams.set('action','query');q.searchParams.set('prop','pageimages');q.searchParams.set('titles',title);q.searchParams.set('pithumbsize','900');q.searchParams.set('pilicense','any');q.searchParams.set('format','json');q.searchParams.set('redirects','1');const r=await fetch(q,{headers:{'User-Agent':'GameGuess-V6/1.0'}});if(!r.ok)continue;const d=await r.json();const pages=Object.values(d?.query?.pages||{});const image=pages[0]?.thumbnail?.source||'';if(image)return image;}return '';}
const FANDOM_WIKIS={db:'dragonball.fandom.com',ygo:'yugioh.fandom.com',naruto:'naruto.fandom.com'};
async function mediaWikiThumb(host,title){const q=new URL(`https://${host}/api.php`);q.searchParams.set('action','query');q.searchParams.set('prop','pageimages');q.searchParams.set('titles',title);q.searchParams.set('pithumbsize','900');q.searchParams.set('format','json');q.searchParams.set('redirects','1');q.searchParams.set('origin','*');try{const r=await fetch(q,{headers:{'User-Agent':'GameGuess-V6/1.0','Accept':'application/json'}});if(r.ok){const d=await r.json();const page=Object.values(d?.query?.pages||{})[0];if(page?.thumbnail?.source)return page.thumbnail.source;}}catch{}
  const p=new URL(`https://${host}/api.php`);p.searchParams.set('action','query');p.searchParams.set('generator','images');p.searchParams.set('titles',title);p.searchParams.set('gimlimit','20');p.searchParams.set('prop','imageinfo');p.searchParams.set('iiprop','url');p.searchParams.set('iiurlwidth','900');p.searchParams.set('format','json');p.searchParams.set('redirects','1');p.searchParams.set('origin','*');try{const r=await fetch(p,{headers:{'User-Agent':'GameGuess-V6/1.0','Accept':'application/json'}});if(!r.ok)return '';const d=await r.json();const pages=Object.values(d?.query?.pages||{});const bad=/logo|icon|symbol|flag|rank|button|portal|wiki|favicon|sprite/i;const ranked=pages.filter(x=>x?.imageinfo?.[0]?.thumburl&&!bad.test(String(x.title||''))).sort((a,b)=>String(a.title||'').length-String(b.title||'').length);return ranked[0]?.imageinfo?.[0]?.thumburl||'';}catch{return '';}}
async function franchiseThumb(series,title){const wiki=await wikiThumb(title);if(wiki)return wiki;const host=FANDOM_WIKIS[String(series||'').toLowerCase()];return host?mediaWikiThumb(host,title):'';}

export default async function handler(req,res){if(!['GET','HEAD'].includes(req.method)){res.setHeader('Allow','GET, HEAD');return j(res,405,{error:'Método não permitido.'});}try{const src=String(req.query?.src||'');let url='';if(src==='lol'){const id=safeId(req.query?.id);if(!id)return j(res,400,{error:'Campeão inválido.'});url=`https://ddragon.leagueoflegends.com/cdn/img/champion/splash/${id}_0.jpg`;}else if(src==='poke'){const id=Number(req.query?.id);if(!Number.isInteger(id)||id<1||id>2000)return j(res,400,{error:'Pokémon inválido.'});url=`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;}else if(src==='digi'){url=allowedDigi(String(req.query?.url||''));if(!url)return j(res,400,{error:'Imagem Digimon inválida.'});}else if(src==='franchise'){const series=String(req.query?.series||'').toLowerCase();const title=String(req.query?.title||'').slice(0,140);if(!FANDOM_WIKIS[series]||!title)return j(res,400,{error:'Personagem inválido.'});url=await franchiseThumb(series,title);if(!url)return j(res,404,{error:'Sem imagem para este personagem.'});}else if(src==='wiki'){const title=String(req.query?.title||'').slice(0,140);if(!title)return j(res,400,{error:'Título inválido.'});url=await wikiThumb(title);if(!url)return j(res,404,{error:'Sem imagem para este personagem.'});}else return j(res,400,{error:'Fonte inválida.'});const up=await fetchBin(url);if(!up.ok)return j(res,up.status===404?404:502,{error:'Imagem indisponível.'});const ct=up.headers.get('content-type')||'image/jpeg';if(!ct.startsWith('image/'))return j(res,502,{error:'Resposta não é imagem.'});res.statusCode=200;res.setHeader('Content-Type',ct);res.setHeader('Cache-Control','public, max-age=86400, s-maxage=604800, stale-while-revalidate=2592000');if(req.method==='HEAD')return res.end();const b=Buffer.from(await up.arrayBuffer());res.setHeader('Content-Length',String(b.length));res.end(b);}catch(e){console.error('asset',e);j(res,e?.name==='AbortError'?504:502,{error:'Falha ao carregar imagem.'});}}
